name: olive-editor
base: core18 # the base snap is the execution environment for this snap
adopt-info: olive
summary: Professional open-source NLE video editor
description: |
  Olive is a non-linear video editor for Windows, macOS, and Linux.

grade: stable
confinement: strict

apps:
  olive-editor:
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      "DISABLE_WAYLAND": "1"
    command: desktop-launch $SNAP/bin/olive-editor
    plugs:
      - opengl
      - desktop
      - desktop-legacy
      - x11
      - network
      - pulseaudio
      - home
      - removable-media
      - unity7

parts:
  olive:
    plugin: qmake
    source: .
    build-packages:
      - qt5-default
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libavformat-dev
      - libavfilter-dev
      - frei0r-plugins-dev
    stage-packages:
      - ffmpeg
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libpulse0
      - libslang2
      - libglu1-mesa
      - frei0r-plugins
    override-build: |
      qmake PREFIX=$SNAPCRAFT_PART_INSTALL
      make
      make install
      snapcraftctl set-version $(git rev-parse --short HEAD)
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5
    - try:
      - appmenu-qt5
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

